---
apiVersion: v1
kind: ConfigMap
metadata:
  name: install-config
  namespace: c7n-system
data:
  install.yml: |-
    version: 0.11
    metadata:
      name: install-all
      namespace: c7n-system
    spec:
      persistence:
        storageClassName: nfs-provisioner
      resources:
        gitlab:
          domain: gitlab.ali.vk.vu
          external: false
          username: root
          schema: http
        minio:
          domain: minio.ali.vk.vu
          schema: http
        harbor:
          domain: harbor.ali.vk.vu
          schema: https
        chartmuseum:
          domain: chart.ali.vk.vu
          schema: http
        api-gateway:
          domain: api.ali.vk.vu
          schema: http
        notify-service:
          domain: notify.ali.vk.vu
          schema: ws
        choerodon-front:
          domain: front.ali.vk.vu
          schema: http
        devops-service:
          domain: devops.ali.vk.vu
          schema: ws
        choerodon-front:
          domain: c7n.ali.vk.vu
          schema: http
        xwiki:
          domain: wiki.ali.vk.vu

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: install-choerodon
  name: install-choerodon
  namespace: c7n-system
spec:
  backoffLimit: 50
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - image: registry.choerodon.com.cn/choerodon-infra/c7n:2018.11.23-095152-master
        imagePullPolicy: Always
        name: install-choerodon
        resources: {}
        volumeMounts:
        - name: config
          mountPath: /etc/c7n/
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: install-config